### ISSUE TITLE
Finalize the input corpus pairs

### ISSUE THREAD

**Issue by soumendrak** [soumendrak/MTEnglish2Odia#9]
The input English-Odia pairs need to be finalized.   
With how many pairs we are going to start.

We should go ahead with 5k curated high-quality pairs.  
It's fine if the pairs are sentences, phrases or words.  

The pairs need to be retrieved from all the [Individual files](https://github.com/OdiaWikimedia/English-Odia/tree/master/data/Individual_files) and the [Combined file](https://github.com/OdiaWikimedia/English-Odia/tree/master/data/Combined_file).  

The final dataset will be added into this repository.

**Comment by soumendrak** [comment]
Mozilla Pontoon English Odia pairs have been added to the [consolidated file](https://github.com/soumendrak/MTEnglish2Odia/blob/master/data/output/combined_file/consolidated_full_corpus.txt)

The Parallel pairs count have been increased to **11,805**.

**Comment by a-parida12** [comment]
Is anyone working on this? Do you think I can work on this?

**Comment by soumendrak** [comment]
@a-parida12 this one is completed. 
You can see this folder for details:
https://github.com/soumendrak/MTEnglish2Odia/tree/master/data/output/organised

Thanks for reaching out. You may look into the other issues or help to prepare step by step instructions for [possible projects](https://github.com/soumendrak/MTEnglish2Odia/blob/master/docs/possible_projects.md). Thank you.
CC: @subhadarship
